{
  "openapi": "3.0.1",
  "info": {
    "title": "API docs",
    "version": "v2"
  },
  "paths": {
    "/api/v1/locations": {
      "get": {
        "summary": "Retrieves the data for the degradation and loss Treemap chart",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "rank_by",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dir",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "start_date",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "end_date",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "location_type",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/location_v1"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error 500",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/error_response"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/locations/{location_id}": {
      "get": {
        "summary": "Retrieves the data for the degradation and loss Treemap chart",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/location_v1"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error 500",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/error_response"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/locations/{location_id}/mangrove_data": {
      "get": {
        "summary": "Retrieves the data for the orginal widgets",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/degradation_and_loss"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error 500",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/error_response"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/spatial_file/converter": {
      "post": {
        "summary": "Converts a geospatial format into a valid geojson",
        "tags": [
          "file_converter"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "type": "FeatureCollection",
                    "features": [
                      {
                        "type": "Feature",
                        "properties": {
                          "id": "ID-1"
                        },
                        "geometry": {
                          "type": "Polygon",
                          "coordinates": [
                            [
                              [
                                100.0,
                                0.0
                              ],
                              [
                                101.0,
                                0.0
                              ],
                              [
                                101.0,
                                1.0
                              ],
                              [
                                100.0,
                                1.0
                              ],
                              [
                                100.0,
                                0.0
                              ]
                            ]
                          ]
                        }
                      },
                      {
                        "type": "Feature",
                        "properties": {
                          "id": "ID-2"
                        },
                        "geometry": {
                          "type": "Polygon",
                          "coordinates": [
                            [
                              [
                                100.0,
                                0.0
                              ],
                              [
                                101.0,
                                0.0
                              ],
                              [
                                101.0,
                                1.0
                              ],
                              [
                                100.0,
                                1.0
                              ],
                              [
                                100.0,
                                0.0
                              ]
                            ]
                          ]
                        }
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/file_converter"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "file"
              }
            }
          },
          "required": true
        }
      }
    },
    "/api/v2/locations": {
      "get": {
        "summary": "Retrieves the data for the biodiversity widget",
        "tags": [
          "Locations"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "meta": {
                    "dates": [
                      {
                        "date": "2016-01-01"
                      }
                    ]
                  },
                  "data": [
                    {
                      "name": "Lome",
                      "location_type": "cum",
                      "iso": "cum",
                      "bounds": {
                      },
                      "location_id": "Location-2",
                      "coast_length_m": 98628.73,
                      "perimeter_m": 98628.73,
                      "area_m2": 98628.73,
                      "id": 15135,
                      "created_at": "2023-05-02T13:18:16.804Z"
                    },
                    {
                      "name": "Kinshasa",
                      "location_type": "voluptatem",
                      "iso": "voluptatem",
                      "bounds": {
                      },
                      "location_id": "Location-1",
                      "coast_length_m": 68950.02,
                      "perimeter_m": 68950.02,
                      "area_m2": 68950.02,
                      "id": 15134,
                      "created_at": "2023-05-02T13:18:16.803Z"
                    }
                  ]
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/location_v2"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a new location",
        "tags": [
          "Locations"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "id": 15141,
                    "iso": "TST",
                    "bounds": null,
                    "location_type": "country",
                    "name": "Test Location",
                    "area_m2": null,
                    "perimeter_m": null,
                    "coast_length_m": null,
                    "location_id": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/location_v2"
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "location_type": {
                    "type": "string"
                  },
                  "iso": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "location_type",
                  "iso"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v2/locations/{location_id}": {
      "get": {
        "summary": "Retrieves the data for the biodiversity widget",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "id": 15143,
                    "iso": "voluptatem",
                    "bounds": {
                    },
                    "location_type": "country",
                    "name": "Kinshasa",
                    "area_m2": 68950.02,
                    "perimeter_m": 68950.02,
                    "coast_length_m": 68950.02,
                    "location_id": "Location-1",
                    "geometry": {
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/location_v2"
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Not Found"
          }
        }
      },
      "put": {
        "summary": "Updates the data of a location",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "id": 15147,
                    "iso": "TST",
                    "bounds": {
                    },
                    "location_type": "country",
                    "name": "Test Location",
                    "area_m2": 68950.02,
                    "perimeter_m": 68950.02,
                    "coast_length_m": 68950.02,
                    "location_id": "Location-1"
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/location_v2"
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Not Found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "location_type": {
                    "type": "string"
                  },
                  "iso": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "location_type",
                  "iso"
                ]
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes a location",
        "tags": [
          "Locations"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Success"
          },
          "400": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/v2/species": {
      "get": {
        "summary": "Retrieves data for species",
        "tags": [
          "Species"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "scientific_name": "voluptatem",
                      "common_name": "voluptatem",
                      "iucn_url": "http://kutch-spencer.com/moises",
                      "red_list_cat": "vu",
                      "location_ids": [
                        15150
                      ]
                    },
                    {
                      "scientific_name": "cum",
                      "common_name": "cum",
                      "iucn_url": "http://bartoletti.com/jeremiah_cronin",
                      "red_list_cat": "lc",
                      "location_ids": [

                      ]
                    }
                  ]
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/specie"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/protected-areas": {
      "get": {
        "summary": "Retrieves the data for the protected area widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "units",
            "in": "query",
            "enum": [
              "km2",
              "ha",
              "m"
            ],
            "description": "Units of result. Default: ha",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "id": 2567,
                      "year": 2016,
                      "total_area": 68950.02,
                      "protected_area": 68950.02
                    }
                  ],
                  "metadata": {
                    "location_id": "15155",
                    "units": {
                      "total_area": "ha",
                      "protected_area": "ha"
                    },
                    "year": [
                      2016
                    ]
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/protected_areas"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/protected-areas/import": {
      "post": {
        "summary": "Uploads the data for Protected areas",
        "tags": [
          "Widgets"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "Import was successful"
          },
          "400": {
            "description": "Location was not found"
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "file"
              }
            }
          },
          "required": true
        }
      }
    },
    "/api/v2/widgets/biodiversity": {
      "get": {
        "summary": "Retrieves the data for the biodiversity widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "total": 1,
                    "threatened": 1,
                    "categories": {
                      "vu": 1
                    },
                    "species": [
                      {
                        "id": 1051,
                        "created_at": "2023-05-02T13:18:17.113Z",
                        "updated_at": "2023-05-02T13:18:17.113Z",
                        "scientific_name": "voluptatem",
                        "common_name": "voluptatem",
                        "iucn_url": "http://kutch-spencer.com/moises",
                        "red_list_cat": "vu"
                      }
                    ]
                  },
                  "metadata": {
                    "unit": null,
                    "note": "nº of species"
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/biodiversity"
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/restoration-potential": {
      "get": {
        "summary": "Retrieves the data for the restoration potential chart",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "description": "Year. Default: last year which contains data",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "restoration_potential_score": 98.63,
                    "restorable_area": 68.96,
                    "restorable_area_perc": null,
                    "mangrove_area_extent": null
                  },
                  "metadata": {
                    "location_id": "15181",
                    "year": [
                      2019,
                      2018
                    ],
                    "units": {
                      "restoration_potential_score": "%",
                      "restorable_area": "%",
                      "mangrove_area": null
                    },
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "$ref": "#/components/schemas/restoration_potential"
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/degradation-and-loss": {
      "get": {
        "summary": "Retrieves the data for the degradation and loss Treemap chart",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "description": "Year. Default: last year which contains data",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "indicator": "degraded_area",
                      "value": 68950.02,
                      "label": "Non-Restorable loss mangrove area"
                    },
                    {
                      "indicator": "lost_area",
                      "value": 13440.899999999994,
                      "label": "Total loss"
                    }
                  ],
                  "metadata": {
                    "location_id": "15209",
                    "year": [
                      2019,
                      2018
                    ],
                    "units": {
                      "degraded_area": "%",
                      "lost_area": "ha",
                      "mangrove_area": "ha"
                    },
                    "main_loss_driver": "Enim repellat pariatur est.",
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/degradation_and_loss"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/blue-carbon-investment": {
      "get": {
        "summary": "Retrieves the data for the blue carbon investment chart",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "units",
            "in": "query",
            "enum": [
              "km2",
              "ha",
              "m"
            ],
            "description": "Units of result. Default: ha",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "category": "carbon_10",
                      "value": 68950.02,
                      "percentage": 100.0,
                      "description": "      68,950.0 (± 3447.501)",
                      "label": "at $10/ton"
                    }
                  ],
                  "metadata": {
                    "location_id": "15243",
                    "unit": "ha",
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/blue_carbon_investment"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/international_status": {
      "get": {
        "summary": "Retrieves the data for the international status widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "ndc_target_url": "voluptatem"
                    }
                  ],
                  "metadata": {
                    "location_id": "15257",
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/international_status"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/ecosystem_services": {
      "get": {
        "summary": "Retrieves the data for the ecosystem services widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "indicator": "voluptatem",
                      "value": 68950.02
                    }
                  ],
                  "metadata": {
                    "location_id": "15265",
                    "unit": "mt CO₂ e",
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ecosystem_service"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/habitat_extent": {
      "get": {
        "summary": "Retrieves the data for the habitat extent widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2019,
                      "indicator": "linear_coverage",
                      "value": 99388.06
                    }
                  ],
                  "metadata": {
                    "location_id": "15280",
                    "units": {
                      "habitat_extent_area": "km2",
                      "linear_coverage": "km"
                    },
                    "year": [
                      2019
                    ],
                    "note": null,
                    "total_area": 0.09938805999999999,
                    "total_lenght": 99.38806
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/habitat_extent"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/net_change": {
      "get": {
        "summary": "Retrieves the data for the net change widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2012,
                      "net_change": 0.0,
                      "gain": null,
                      "loss": null
                    },
                    {
                      "year": 2013,
                      "net_change": -14200.229999999996,
                      "gain": null,
                      "loss": null
                    }
                  ],
                  "metadata": {
                    "location_id": "15298",
                    "units": {
                      "net_change": "km2"
                    },
                    "year": [
                      1996,
                      2007,
                      2008,
                      2009,
                      2010,
                      2015,
                      2016,
                      2017,
                      2018,
                      2019,
                      2020
                    ],
                    "note": null,
                    "total_area": 0.09938805999999999,
                    "total_lenght": 99.38806
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/net_change"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/aboveground_biomass": {
      "get": {
        "summary": "Retrieves the data for the aboveground_biomass widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2019,
                      "indicator": "150-250",
                      "value": 99388.06
                    }
                  ],
                  "metadata": {
                    "location_id": "15316",
                    "units": {
                      "value": "tons/ha"
                    },
                    "year": [
                      2019
                    ],
                    "note": null,
                    "total_aboveground_biomass": [

                    ],
                    "avg_aboveground_biomass": [

                    ]
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/aboveground_biomass"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/tree_height": {
      "get": {
        "summary": "Retrieves the data for the tree height widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2016,
                      "indicator": "0-5",
                      "value": 99388.06
                    }
                  ],
                  "metadata": {
                    "location_id": "15332",
                    "units": {
                      "value": "m"
                    },
                    "year": [
                      2016
                    ],
                    "note": null,
                    "avg_height": [

                    ]
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/tree_height"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/blue_carbon": {
      "get": {
        "summary": "Retrieves the data for the blue carbon widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2019,
                      "indicator": "molestiae",
                      "value": 99388.06
                    }
                  ],
                  "metadata": {
                    "location_id": "15344",
                    "units": {
                      "value": "CO2e/ha",
                      "toc": "t CO₂e",
                      "soc": "t CO₂e",
                      "agb": "t CO₂e"
                    },
                    "year": [
                      2019
                    ],
                    "note": null,
                    "toc": 85187.83
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/blue_carbon"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/mitigation_potentials": {
      "get": {
        "summary": "Retrieves the data for the mitigation potential widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "location_id",
            "in": "query",
            "description": "Location id. Default: worldwide",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "year": 2016,
                      "indicator": "Reduce mangrove loss",
                      "category": "Other",
                      "value": 68950.02
                    }
                  ],
                  "metadata": {
                    "location_id": "15355",
                    "units": {
                      "value": "tCO2/ha"
                    },
                    "year": [
                      2016
                    ],
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/mitigation_potentials"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/widgets/country_ranking": {
      "get": {
        "summary": "Retrieves the data for the mitigation potential widget",
        "tags": [
          "Widgets"
        ],
        "parameters": [
          {
            "name": "start_year",
            "in": "query",
            "description": "Location id. Default: first year that data exists for",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "end_year",
            "in": "query",
            "description": "Location id. Default: last year that dat exists for",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": [
                    {
                      "value": 30438.039999999994,
                      "abs_value": 30438.039999999994,
                      "name": "Kinshasa",
                      "indicator": "net_change",
                      "iso": "voluptatem",
                      "id": null
                    }
                  ],
                  "metadata": {
                    "units": {
                      "value": "km2"
                    },
                    "years": [
                      2010,
                      2015,
                      2016,
                      2020
                    ],
                    "start_year": 2010,
                    "end_year": 2020,
                    "note": null
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/country_ranking"
                      }
                    },
                    "metadata": {
                      "type": "object",
                      "$ref": "#/components/schemas/metadata"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://mangrove-atlas-api-staging.herokuapp.com",
      "description": "staging api url"
    },
    {
      "url": "https://mangrove-atlas-api.herokuapp.com",
      "description": "production api url"
    }
  ],
  "components": {
    "schemas": {
      "metadata": {
        "type": "object",
        "properties": {
          "location_id": {
            "type": "string",
            "nullable": true
          },
          "unit": {
            "type": "string",
            "nullable": true
          },
          "units": {
            "type": "object",
            "nullable": true
          },
          "years": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "nullable": true
          },
          "note": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "error_response": {
        "type": "object",
        "properties": {
          "error": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string",
                "nullable": true
              }
            }
          }
        },
        "required": [
          "error"
        ]
      },
      "location_v1": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "joiningDate": {
            "type": "string"
          },
          "homeAddress": {
            "type": "object",
            "properties": {
              "address1": {
                "type": "string"
              },
              "address2": {
                "type": "string",
                "nullable": true
              },
              "city": {
                "type": "string"
              },
              "state": {
                "type": "string"
              },
              "postalCode": {
                "type": "string"
              }
            },
            "required": [

            ]
          },
          "medicareRequested": {
            "type": "boolean"
          },
          "compensationUsdCents": {
            "type": "integer",
            "description": "compensation"
          }
        },
        "required": [

        ]
      },
      "location_v2": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "created_at": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "location_type": {
            "type": "string"
          },
          "iso": {
            "type": "string"
          },
          "location_id": {
            "type": "string",
            "nullable": true
          },
          "coast_length_m": {
            "type": "number",
            "nullable": true
          },
          "area_m2": {
            "type": "number",
            "nullable": true
          }
        },
        "required": [

        ]
      },
      "specie": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "scientific_name": {
            "type": "string"
          },
          "common_name": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "iucn_url": {
            "type": "string",
            "nullable": true
          },
          "red_list_cat": {
            "type": "string"
          },
          "location_ids": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          }
        }
      },
      "protected_areas": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "nullable": true
          },
          "year": {
            "type": "integer"
          },
          "total_area": {
            "type": "number"
          },
          "protected_area": {
            "type": "number"
          }
        },
        "required": [

        ]
      },
      "biodiversity": {
        "type": "object",
        "properties": {
          "total": {
            "type": "integer"
          },
          "threatened": {
            "type": "integer"
          },
          "categories": {
            "type": "object",
            "properties": {
              "cr": {
                "type": "integer",
                "nullable": true
              },
              "en": {
                "type": "integer",
                "nullable": true
              },
              "nt": {
                "type": "integer",
                "nullable": true
              },
              "lc": {
                "type": "integer",
                "nullable": true
              }
            }
          },
          "species": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/specie"
            }
          }
        },
        "required": [
          "total",
          "threatened",
          "categories"
        ]
      },
      "restoration_potential": {
        "type": "object",
        "properties": {
          "restoration_potential_score": {
            "type": "number"
          },
          "restorable_area": {
            "type": "number",
            "nullable": true
          },
          "restorable_area_perc": {
            "type": "number",
            "nullable": true
          },
          "mangrove_area_extent": {
            "type": "number",
            "nullable": true
          }
        },
        "required": [
          "restoration_potential_score",
          "restorable_area",
          "restorable_area_perc",
          "mangrove_area_extent"
        ]
      },
      "degradation_and_loss": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "value": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value"
        ]
      },
      "blue_carbon_investment": {
        "type": "object",
        "properties": {
          "category": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "percentage": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "label": {
            "type": "string"
          }
        },
        "required": [
          "category",
          "value",
          "percentage",
          "description"
        ]
      },
      "international_status": {
        "type": "object",
        "properties": {
          "base_years": {
            "type": "string"
          },
          "fow": {
            "type": "string"
          },
          "frel": {
            "type": "string"
          },
          "ipcc_wetlands_suplement": {
            "type": "string"
          },
          "ndc": {
            "type": "string"
          },
          "ndc_adaptation": {
            "type": "string"
          },
          "ndc_blurb": {
            "type": "string"
          },
          "ndc_mitigation": {
            "type": "string"
          },
          "ndc_reduction_target": {
            "type": "string"
          },
          "ndc_target": {
            "type": "string"
          },
          "ndc_target_url": {
            "type": "string"
          },
          "ndc_updated": {
            "type": "string"
          },
          "pledge_summary": {
            "type": "string"
          },
          "pledge_type": {
            "type": "string"
          },
          "target_years": {
            "type": "string"
          },
          "year_frel": {
            "type": "string"
          }
        }
      },
      "ecosystem_service": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value"
        ]
      },
      "habitat_extent": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "year": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value",
          "year"
        ]
      },
      "net_change": {
        "type": "object",
        "properties": {
          "net_change": {
            "type": "number"
          },
          "year": {
            "type": "number"
          },
          "gain": {
            "type": "number",
            "nullable": true
          },
          "loss": {
            "type": "number",
            "nullable": true
          }
        },
        "required": [
          "net_change",
          "year"
        ]
      },
      "aboveground_biomass": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "year": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value",
          "year"
        ]
      },
      "tree_height": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "year": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value",
          "year"
        ]
      },
      "blue_carbon": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "year": {
            "type": "number"
          }
        },
        "required": [
          "indicator",
          "value",
          "year"
        ]
      },
      "mitigation_potentials": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "year": {
            "type": "number"
          },
          "category": {
            "type": "string"
          }
        },
        "required": [
          "indicator",
          "value",
          "year",
          "category"
        ]
      },
      "country_ranking": {
        "type": "object",
        "properties": {
          "indicator": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "abs_value": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "iso": {
            "type": "string"
          }
        },
        "required": [
          "indicator",
          "value"
        ]
      },
      "file_converter": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "features": {
            "type": "array",
            "items": {
              "type": "object"
            },
            "nullable": false
          }
        },
        "required": [
          "type",
          "features"
        ]
      }
    }
  }
}